#!/bin/bash
# -*- sh -*-

rpmsystem=$(hostname)
rpmsystem=${rpmsystem#*.} # remove build or staff
rpmsystem=${rpmsystem%%.*} # remove tacc.utexas.edu

function usage () {
    echo "Usage: make_download [ -c Configuration ] [ -v version ] [ -z (for zip) ] package"
}

if [ $# -eq 0 -o "$1" = "-h" ] ; then
   exit 0
fi

configuration=
zip=0
while [ $# -gt 1 ] ; do
    if [ "$1" = "-h" ] ; then
        echo "Usage: make_download [ -v version ] [ -z ] package"
        exit 0
    elif [ "$1" = "-c" ] ; then
        shift && configuration=$1 && shift
    elif [ "$1" = "-v" ] ; then
        shift && version=$1 && shift
    elif [ "$1" = "-z" ] ; then
        zip=1 && shift
    fi
done

## set -x
package=$1
if [ -z "$package" ] ; then
    usage && exit 1
fi
rpms=/admin/build/admin/rpms/${rpmsystem}
scripts=${rpms}/SPECS/RPMtheNextGeneration

if [ ! -d ${scripts}/makefiles/$package ] ; then
    echo "Could not find directory: $package"
    exit 1
fi

export PATH=$(pwd)/MrPackMod:${PATH}
export PYTHONPATH=$(pwd):${PYTHONPATH}
cd ${scripts}/makefiles/$package

# From now on only MrPackMod installations

pkgversion=$( \
    DOWNLOADPATH=${rpms}/SOURCES \
         TACC_FAMILY_COMPILER=intel \
         PACKAGEROOT=${rpms} PACKAGE=${package} \
         mpm.py version \
         )
if [ ! -z "${version}" ] ; then
    pkgversion=${version}
fi

DOWNLOADPATH=${rpms}/SOURCES \
 TACC_FAMILY_COMPILER=intel \
 PACKAGEROOT=${rpms} PACKAGE=${package} \
 PACKAGEVERSION=${pkgversion} \
 PACKAGEVERSION_DOWNLOAD=${pkgversion} \
 mpm.py -t \
     $( if [ ! -z "${configuration}" ] ; then echo "-c ${configuration}" ; fi ) \
     download unpack retar


